config/routes.rb
Rails.application.routes.draw do
  get '/books', to: 'books#index'
  get '/books/new', to: 'books#new'
  post '/books', to: 'books#create'
  get '/books/:id/modify', to: 'books#modify', as: :modify_books
  patch '/books/:id', to: 'books#update', as: :book
  delete '/books/:id', to: 'books#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
    end

    def new
    end

    def create
        # Retrieve the book parameters that we submit in the form
        title = params[:title]
        description = params[:description]
        author = params[:author]

        # Create a new record in the database with this parameters
        Book.create(title: title, description: description, author: author)
        
        # And then redirect to the index page
        redirect_to books_path
    end
    def modify
        # Retrieve the current book
        @book = Book.find(params[:id])
    end
    def update
       # Retrieve the current book
        @book = Book.find(params[:id])

        # update the record in the database with this parameters
        @book.update(title: params[:book][:title], description: params[:book][:description], author: params[:book][:author])
        
        # And then redirect to the index page
        redirect_to books_path
    end
    def destroy
        @book = Book.find(params[:id])
        
        @book.destroy

        redirect_to books_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<h1>Books</h1>
<%= button_to 'New book', books_new_path, method: :get %>
<% Book.all.each do |book| %>
    <p>Title : <%=book.title%></p>
    <p>Author : <%=book.author%></p>
    <p>Description : <%=book.description%></p>
    <p><%=book.reading_status%></p>
    <%= button_to 'Modify', modify_books_path(book), method: :get %>
    <%= button_to 'Delete', book, method: :delete %>
    ______________________________
<% end %>

app/views/books/modify.html.erb
<%= link_to 'Back', books_path %>
<%= form_with model: @book do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :author %>
    <%= form.text_field :author %>
    <%= form.label :description %>
    <%= form.text_field :description %>
    <%= form.submit %>
<% end %>

app/views/books/new.html.erb
<%= link_to 'Back', books_path %>
<%= form_with url: books_path do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :author %>
    <%= form.text_field :author %>
    <%= form.label :description %>
    <%= form.text_field :description %>
    <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>